### ISSUE TITLE
No longer require('pixi.js')

### ISSUE THREAD

**Issue by englercj** [JiDW/pixi-cocoontext#1]
Heads up: No longer do `require('pixi.js')`, just use PIXI as an implicit global. You can see these issues for more details:

https://github.com/GoodBoyDigital/pixi.js/issues/1713
https://github.com/pixijs/pixi-spine/issues/20

**Comment by JiDW** [comment]
Thanks, Fixed https://github.com/JiDW/pixi-cocoontext/commit/adf139b648617d1b1a6d64e6ba21560a3cfb8324

**Comment by englercj** [comment]
Nice, also will want to remove the external call in your build scripts:

https://github.com/JiDW/pixi-cocoontext/blob/master/gulp/util/bundle.js#L28-L30

**Comment by JiDW** [comment]
Oh yes, thank you, I didn't see that one !
